window.BASTION_DOM = {
  get(id, fallbackTag = 'div', defaults = {}) {
    let element = document.getElementById(id);

    if (!element) {
      element = document.createElement(fallbackTag);
      element.id = id;
      element.hidden = true;
      element.dataset.autogenerated = 'true';
      document.body.appendChild(element);
    }

    Object.entries(defaults).forEach(([key, value]) => {
      if (key in element) {
        element[key] = value;
      } else {
        element.setAttribute(key, value);
      }
    });

    return element;
  },

  on(element, event, handler) {
    if (!element || typeof handler !== 'function') return false;
    element.addEventListener(event, handler);
    return true;
  }
};
